# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontogen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='mapping',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pattern',
            name='pattern',
            field=models.TextField(default=''),
        ),
    ]
