# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontogen', '0003_auto_20170312_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='mapping',
            field=models.CharField(max_length=100),
        ),
    ]
