# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontogen', '0005_auto_20170312_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='pattern_label',
            field=models.CharField(default='pattern', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mapping',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='ontogen.Pattern'),
        ),
    ]
