# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontogen', '0006_auto_20170312_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='instruction_label',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instruction',
            name='instruction_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
