# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontogen', '0007_auto_20170312_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontogen.Pattern')),
            ],
        ),
    ]
