# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontogen', '0008_generatorconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatorconfig',
            name='patterns',
            field=models.ManyToManyField(to='ontogen.Pattern'),
        ),
        migrations.AlterField(
            model_name='generatorconfig',
            name='instruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontogen.Instruction'),
        ),
    ]
