# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontogen', '0009_auto_20170312_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='extracted_elements_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
