# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ontogen', '0011_auto_20170409_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyrecord',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
