# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-18 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontogen', '0015_instruction_instruction_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='FramesetGranule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[(None, '-'), ('cont', 'Container'), ('term', 'Terminal')], default='term', max_length=4)),
                ('first_frame', models.CharField(max_length=200)),
                ('last_frame', models.CharField(max_length=200)),
                ('child_granules', models.ManyToManyField(related_name='_framesetgranule_child_granules_+', to='ontogen.FramesetGranule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GranuleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='framesetgranule',
            name='elements',
            field=models.ManyToManyField(to='ontogen.GranuleItem'),
        ),
    ]
